builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -extldflags "-static"
  main: main.go
  binary: bin/{{ .ProjectName }}
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - 386
  - arm
  - arm64
  goarm:
  - 5
  - 6
  - 7
  ignore:
  - goos: freebsd
    goarch: arm
  - goos: windows

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archive:
  format: tar.gz
  files:
  - README.md
