language: go
go:
- 1.12.x
install:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
script:
- golangci-lint run --disable-all --enable=vet --enable=ineffassign --enable=goconst --tests ./...
- go test -v -race ./...
before_script:
- echo "REPO $TRAVIS_REPO_SLUG TAG ${TRAVIS_TAG}"
before_deploy:
- go get github.com/goreleaser/goreleaser
deploy:
- provider: script
  script: goreleaser
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai
- bonsai/generate-sha512sum.sh
- bonsai/github-release-upload.sh github_api_token=$GITHUB_TOKEN repo_slug="$TRAVIS_REPO_SLUG"
  tag="${TRAVIS_TAG}" filename="dist/$(cat dist/sha512_file)"
env:
  global:
    - GO111MODULE=on
